### ISSUE TITLE
About the mockserver

### ISSUE THREAD

**Issue by YufeeXing** [pactflow/example-consumer#112]
https://github.com/pactflow/example-consumer/blob/07112a44d96580addc7b25d89f7dd2be1c91a4aa/src/api.pact.spec.js#L45

Hello, I wonder when this return function will be execute and how to configure this mockserver paramter passed in this callback function.

**Comment by mefellows** [comment]
The framework configures the mock server dynamically (well, it allocates a random port) or uses the information given to the Pact constructor and passes it to your function. Your function then uses those details to configure your API client, which you then use to make a call to the mock server and unit test your client.

Best to ask these questions elsewhere, this is just a test project.

I'd recommend joining slack.pact.io 👋
