### ISSUE TITLE
[BUG] Unable to setup front end for consumer due to js error

### ISSUE THREAD

**Issue by jithinjosejacob** [pactflow/example-consumer#46]
Issue: [BUG] Unable to setup front end for consumer due to js error

Steps to Repo

Clone repo to local and set up the consumer using npm install and npm start

Platform: Windows

User gets and error : Failed prop type: Invalid prop `children` of type `array` supplied to `Layout`, expected a single ReactElement type

**Comment by mefellows** [comment]
Thanks Jithin. It should be fairly ease to resolve, my guess is we haven't pinned a react dependency. If you could try a `npm ci` with a fresh node modules to see if it works it might be as simple as that

**Comment by mefellows** [comment]
See also https://github.com/pact-foundation/pact-workshop-js/issues/3

**Comment by jithinjosejacob** [comment]
i am getting the same error as i mentioned in the initial bug, it looks like not unrelated to above workshop issue, tried in mac as well

**Comment by mefellows** [comment]
Actually, I think the issue here is that you don't have your provider running and the react warning is just that. The canonical provider is https://github.com/pactflow/example-provider but you can mix and match many (see https://docs.pactflow.io/docs/examples/).

**Comment by mefellows** [comment]
I can't reproduce with those instructions. 

I can see the bug report is `http://localhost:3000/error`. If the provider is unavailable when you first open the app, it will route to this page. Can you please show the network tab or capture a full HAR from the chrome dev tools when you navigate to `/`?

**Comment by jithinjosejacob** [comment]
Provider is running , then only i opened the consumer 

<img width="1063" alt="Screen Shot 2022-04-19 at 4 51 35 pm" src="https://user-images.githubusercontent.com/42768797/163943330-b4781f14-6ff6-469d-a3d4-79a384193b20.png">
<img width="1208" alt="Screen Shot 2022-04-19 at 4 53 53 pm" src="https://user-images.githubusercontent.com/42768797/163943657-db23e3dd-0907-4043-a173-de4c96951f5c.png">

No specific network erros as well.

**Comment by mefellows** [comment]
What happens if you run `curl localhost:3000` or open in another browser? I've noticed sometimes Chrome will redirect to `/error` because it previously detected a redirect.

**Comment by jithinjosejacob** [comment]
<img width="1181" alt="Screen Shot 2022-04-19 at 5 15 27 pm" src="https://user-images.githubusercontent.com/42768797/163946911-c38adae0-cc2a-434d-81be-cf029a40c3dd.png">
There is a network error on products call,  loom- https://www.loom.com/share/08a190061d4549d5bafe32bc3657b3cf
shared the har in slack

**Comment by mefellows** [comment]
Thanks for that.

I can see the problem - it’s trying to send requests to localhost:3001.

The example is actually part of this [workshop](https://docs.pactflow.io/docs/workshops/ci-cd/), and one of the steps describes how to configure it to point at the locally running provider: https://docs.pactflow.io/docs/workshops/ci-cd/set-up-local-development/run-the-applications

I'm not sure why it doesn't use the default, but likely there was a good reason.

I’ll update the README so people coming from a different source will know what to do (or I'll update the api.js file to change the default if it makes sense).

Hope this helps!

I'll leave it open so you can confirm.

**Comment by jithinjosejacob** [comment]
thanks, this works, probabaly good to update readme

**Comment by mefellows** [comment]
Have updated the readme. Note, there was already a `Usage` section that linked to how to run this in detail, however I've specifically brought in the section on how to run it locally.
